spring:
  datasource:
    url: "jdbc:h2:mem:test;DB_CLOSE_DELAY=-1"
    driver-class-name: "org.h2.Driver"
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    database: h2
    show-sql: false
    hibernate:
      ddl-auto: create


STREAMLABS_ACCESS_TOKEN: sZW6Hpr4FeAkqjVZreg2iosvOTAYOHzCqqbRBqGb
STREAMLABS_CLIENT_ID: 123
STREAMLABS_CLIENT_SECRET: 123
VIPPS_CALLBACK_PREFIX: https://vipps-streamlabs-backend.azurewebsites.net/
VIPPS_CLIENT_ID: 1cca1cae-f88c-4f09-a6fb-770b7b17a6e2
VIPPS_CLIENT_SECRET: MmRIbkVCSzNHb0pXemdZOEhiMjA=
VIPPS_FALLBACK_URL: https://vipps-streamlabs-frontend.azurewebsites.net/fallback
VIPPS_MERCHANT_SERIAL_NUMBER: 565589
VIPPS_OCP_APIM_SUBSCRIPTION_KEY_ACCESSTOKEN: efee3020a37644c49b39d25d387faab3
VIPPS_OCP_APIM_SUBSCRIPTION_KEY_ECOMMERCE: d85f2e204ffe4486ab7873616c646ccf
TRANSACTION_TEXT: "Donasjon til Emzia"
STREAMER_NAME: "Emzia"

